### PR TITLE
fix Javers support

### LINKED ISSUE #70: javers support not working anymore
Running the generator and selecting Javers auditing framework fails with:

```
ERROR! Copying template src/main/java/package/web/rest/_JaversEntityAuditResource.java failed. [ReferenceError: /home/gimoh/wrk/github.com/gimoh/generator-jhipster-entity-audit/generators/app/templates/src/main/java/package/web/rest/_JaversEntityAuditResource.java:58
    56|     public List<String> getAuditedEntities() {
    57| 
 >> 58|       return Arrays.asList(<%- auditedEntities %>);
    59|     }
    60| 
    61|     /**
```

After commit 72d0ae8a7db414308325b95005bd6252600640ea `auditedEntities` is now assigned inside `utils.js` in `#updateEntityAudit` but only conditionally and when I run it both conditions are false, i.e. `updateIndex === undefined` and ``this.fs.exists(`${javaDir}web/rest/JaversEntityAuditResource.java`) === false``.

I can submit a PR but will need some guidance on what the code is supposed to do. Could this block to update list of audited entities be moved out of `updateEntityAudit` and back into the main? In fact, would it make sense to put it into `#writeAuditPageFiles`?

### PR DESCRIPTION
**Pull request by gimoh**
Update Javers support to work after recent refactoring by making both the main generator and the :entity subgenerator populate and update `auditedEntities` array which is used in the template.

Minor refactoring:

- move `copyFiles` to `utils.js` for reusability
- rename `entitiesToUpdate` in main generator to `auditedEntities` to match the variable name used in :entity subgenerator and the `JaversEntityAuditResource` template

This also required an update to Javers 3.5.0 in order to bring in support for new `java.time` classes. Supersedes #58 

Fixes #70

### CODE REVIEW

File: generators/app/index.js [hunk 1]
```diff
@@ -294,15 +285,24 @@ module.exports = JhipsterAuditGenerator.extend({
...
+        this.auditedEntities.forEach((entityName) => {
+          const entityFile = `.jhipster/${entityName}.json`;
+          jsonObj = this.fs.readJSON(entityFile);
+
+          // flag this entity as audited so the :entity subgenerator
+          // can pick up all audited entities
+          // technically this is only needed for Javers, as the custom
+          // framework obtains this list at runtime using
+          // `EntityAuditEventRepository.findAllEntityTypes`;
+          this.updateEntityConfig(entityFile, 'enableEntityAudit', true);
```
Comment (deepu105) [inline generators/app/index.js]: want this already done somewhere?

Comment (gimoh) [inline generators/app/index.js]: That's the thing, I couldn't find it, in fact when I ran the main generator at first it didn't update my entity json files at all, that's why I initially thought we weren't storing the information about which entities should be audited anywhere.

Comment (gimoh) [inline generators/app/index.js]: I just did a history search and it looks like this was ever only set from the :entity subgenerator.

**Comment by gimoh** [comment]
@deepu105 @atomfrede any word on this? I'm almost ready with Angular 4 port, but it's based on this one

**Comment by atomfrede** [comment]
Sorry for the delay will have a look later today.

File: generators/app/index.js (hunk 1 above)
Comment (atomfrede) [inline generators/app/index.js]: @gimoh You are right. Looks all good to me.

**Comment by atomfrede** [comment]
Looks good to me. Have restarted the travis job as it does look like a travis problem.

**Comment by gimoh** [comment]
@atomfrede no worries at all, just checking

**Comment by atomfrede** [comment]
Maybe has something to do with instant and locale date conversation

**Comment by deepu105** [comment]
@atomfrede @gimoh yes the ES tests are always failing and I couldnt figure out why. So for now I removed ES from the test config. I have no clue on why its fails here, its been failing from the very beginning

**Comment by gimoh** [comment]
@atomfrede @deepu105 thank you guys 🎉 I'll sumbit the Angular 4 port shortly
