### PR TITLE
Various fixes and upgrades

### LINKED ISSUE #140: [@fortawesome/angular-fontawesome] update from <i class="fa ..."> to <fa-icon icon=...>
```
// entity-audit.component.html
<!--<i class="fa fa-refresh"></i>&nbsp;-->
<fa-icon icon="sync"></fa-icon>&nbsp;

<!--<i class="fa fa-eye"></i>-->
<fa-icon icon="eye"></fa-icon>

// navbar.component.html
// change it to be consistent to other fa-icon declarations
<!--<fa-icon [icon]="'list-alt'" [fixedWidth]="true"></fa-icon>&nbsp;-->
<fa-icon icon="list-alt" fixedWidth="true"></fa-icon>&nbsp;

```

### LINKED ISSUE #142: Menu entry "Admin Entity Audit" does not work
Same environment as in #138, tested also with entity audit 3.2.0

Click on menu entry "Administration" -> "Admin Entity Audit" does not have any effect.

### PR DESCRIPTION
**Pull request by kaidohallik**
Made some fixes and enhancements:
* add `Prettier` transform to format generated code
* use `skipServer` and `skipServer` from config to generate front end only if not skipping client and back end only if not skipping server
* use `jhiPrefix` from config everywhere instead of using constant prefix `jhi` in some places
* removed some extra spaces from `jhipster-needle-add-admin-route` code so that in regeneration no double code any more
* fix #142 which occurred when i18n was not enabled
* fix #140 (icon cleaning in the admin menu is performed by jhipster/generator-jhipster#11210)
* remove `CUSTOM_ELEMENTS_SCHEMA` because no custom schema is used
* upgrade `yeoman-generator` dependency to version `4.5.0` to keep it in sync with `generator-jhipster`
* load user choices from config and don't ask again already answered questions
* save also `auditPage` variable to config
* registering also post app hook so that after app upgrade is entity audit support generated automatically

In `generator-jhipster` opened PR-s to better support this module:
* jhipster/generator-jhipster#11210 - if this is merged then icon appears in the admin menu for entity audit
* jhipster/generator-jhipster#11205 - if regenerating in Windows then don't add double code

### CODE REVIEW

File: generators/app/index.js [hunk 1]
```diff
@@ -395,42 +415,45 @@ module.exports = class extends BaseGenerator {
...
         }
       },
 
       registering() {
         // Register this generator as a dev dependency
         this.addNpmDevDependency('generator-jhipster-entity-audit', packagejs.version);
-        // Register post-entity hook
+        // Register post-app and post-entity hook
         try {
+          this.registerModule('generator-jhipster-entity-audit', 'app', 'post', 'app', 'Add support for entity audit and audit log page');
```
Comment (murdos) [inline generators/app/index.js]: That's interesting. So it means that most module should register themselves as a post-app hook I guess.

**Comment by kaidohallik** [comment]
Thanks a lot for the review and for merging @murdos !

Sorry about not splitting PR to smaller commits, next time I try to keep that in mind.
